import { defineConfig } from 'oxfmt'
import ultracite from 'ultracite/oxfmt'

// Same formatting as the rarv repo, so ui components can be copied between the
// two without a reformat: tabs, 120 columns, single quotes, no semicolons.
export default defineConfig({
	...ultracite,
	ignorePatterns: [
		'node_modules/**/*',
		'dist/**/*',
		'build/**/*',
		'*.md',
		'*.gen.ts',
		'*.conf',
		'*.lock',
		'*.svg',
		'*.sql',
		'*.yml',
		'*.yaml',
		'*.env',
		'*.env.*',
		'*.log',
		'*.sh',
	],
	arrowParens: 'avoid',
	bracketSameLine: false,
	bracketSpacing: true,
	semi: false,
	singleQuote: true,
	jsxSingleQuote: true,
	quoteProps: 'as-needed',
	trailingComma: 'all',
	singleAttributePerLine: false,
	htmlWhitespaceSensitivity: 'strict',
	vueIndentScriptAndStyle: true,
	proseWrap: 'never',
	insertPragma: false,
	printWidth: 120,
	requirePragma: false,
	tabWidth: 4,
	useTabs: true,
	embeddedLanguageFormatting: 'auto',
	endOfLine: 'lf',
	insertFinalNewline: true,
	sortImports: {
		customGroups: [
			{ groupName: 'app-assets', elementNamePattern: ['@/assets', '@/assets/**'] },
			{ groupName: 'react', elementNamePattern: ['react', 'react/**'] },
			{ groupName: 'app-components-icons', elementNamePattern: ['@/components/icons', '@/components/icons/**'] },
			{ groupName: 'app-components', elementNamePattern: ['@/components', '@/components/**'] },
			{ groupName: 'app-hooks', elementNamePattern: ['@/hooks', '@/hooks/**'] },
			{ groupName: 'app-lib', elementNamePattern: ['@/lib', '@/lib/**'] },
			{ groupName: 'app-utils', elementNamePattern: ['@/utils', '@/utils/**'] },
			{ groupName: 'app-types', elementNamePattern: ['@/types', '@/types/**'] },
			{ groupName: 'app-services', elementNamePattern: ['@/services', '@/services/**'] },
			{ groupName: 'app-routes', elementNamePattern: ['@/routes', '@/routes/**'] },
			{ groupName: 'relative', elementNamePattern: ['.', '..', './*', './**', '../*', '../**'] },
		],
		groups: [
			'builtin',
			'app-assets',
			'react',
			'external',
			'app-components',
			'app-components-icons',
			'app-hooks',
			'app-lib',
			'app-utils',
			'app-types',
			'app-services',
			'app-routes',
			'internal',
			'relative',
			'unknown',
		],
		newlinesBetween: false,
		order: 'asc',
		ignoreCase: true,
	},
	sortTailwindcss: {
		stylesheet: './apps/web/src/styles.css',
		attributes: ['class', 'className'],
		functions: ['clsx', 'cn', 'cva', 'tw'],
		preserveDuplicates: false,
		preserveWhitespace: false,
	},
	sortPackageJson: {
		sortScripts: true,
	},
})
