package projects

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vexdock/platform/manager/internal/database"
	"github.com/vexdock/platform/manager/internal/engines"
	"github.com/vexdock/platform/manager/internal/security"
)

// overlayFileName is the compose file the manager writes from the service rows
// the dashboard owns. It is layered over the project's own compose file with a
// second --file flag, so an imported compose keeps working untouched and can
// still gain a database next to it.
const overlayFileName = "managed.yml"

// servicesDirName holds one checkout and one env file per managed service.
const servicesDirName = "services"

// ServiceDir is where a managed service keeps its own state, currently its git
// checkout. Kept separate from the project-level repository/ so two services
// can build from two different repositories.
func (s *Service) ServiceDir(env *database.Environment, name string) string {
	return filepath.Join(s.cfg.ProjectDir(env.ID), servicesDirName, name)
}

// ServiceEnvFilePath is the env file a managed service hands to its container.
// Per service rather than per project so two Postgres services in one project
// can each define POSTGRES_PASSWORD.
func (s *Service) ServiceEnvFilePath(env *database.Environment, name string) string {
	return filepath.Join(s.cfg.ProjectDir(env.ID), servicesDirName, name+".env")
}

// WriteOverlay renders every managed service of a project into the overlay
// compose file and writes each service's env file alongside it. It returns the
// overlay path, or an empty string when the project has no managed services and
// the project's own compose file is the whole story.
func (s *Service) WriteOverlay(ctx context.Context, env *database.Environment) (string, error) {
	all, err := s.db.ListServices(ctx, env.ID)
	if err != nil {
		return "", err
	}
	managed := make([]database.Service, 0, len(all))
	for _, svc := range all {
		// An application whose source is still unanswered has nothing to render,
		// and emitting an empty service would fail the whole project's deploy.
		if svc.Managed() && svc.SourceType != database.ServiceUnconfigured {
			managed = append(managed, svc)
		}
	}
	path := filepath.Join(s.cfg.ProjectDir(env.ID), overlayFileName)
	if len(managed) == 0 {
		// Leaving a stale overlay behind would resurrect a deleted service on
		// the next deploy.
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return "", err
		}
		return "", nil
	}
	sort.Slice(managed, func(i, j int) bool {
		return managed[i].ComposeServiceName < managed[j].ComposeServiceName
	})

	if err := os.MkdirAll(filepath.Join(s.cfg.ProjectDir(env.ID), servicesDirName), 0o750); err != nil {
		return "", err
	}

	var body strings.Builder
	body.WriteString("# Generated by vexdock. Edits are overwritten on deploy.\nservices:\n")
	volumes := []string{}
	for _, svc := range managed {
		if err := s.writeServiceEnv(ctx, env, svc); err != nil {
			return "", err
		}
		fragment, vols, err := s.renderService(env, svc)
		if err != nil {
			return "", fmt.Errorf("service %s: %w", svc.ComposeServiceName, err)
		}
		// The catalog fragments are raw string literals that stop on their last
		// content character, so the next service's key would land on the previous
		// one's last line. Normalise here, where all three render branches meet.
		fmt.Fprintf(&body, "  %s:\n%s\n", svc.ComposeServiceName, strings.TrimRight(fragment, "\n"))
		volumes = append(volumes, vols...)
	}
	if len(volumes) > 0 {
		body.WriteString("\nvolumes:\n")
		seen := make(map[string]struct{}, len(volumes))
		for _, v := range volumes {
			if _, ok := seen[v]; ok {
				continue
			}
			seen[v] = struct{}{}
			fmt.Fprintf(&body, "  %s: {}\n", v)
		}
	}
	// Same temp-and-rename as nginx and acme use: docker compose reads this
	// file, and a half-written one fails the whole project, not one service.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body.String()), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", err
	}
	return path, nil
}

// renderService turns one service row into its compose body, indented four
// spaces, plus the named volumes it needs declared at the top level.
func (s *Service) renderService(env *database.Environment, svc database.Service) (string, []string, error) {
	switch svc.SourceType {
	case database.ServiceImage, database.ServiceGit:
	case database.ServiceCompose:
		vols, err := namedVolumes(svc.ComposeFragment)
		if err != nil {
			return "", nil, err
		}
		fragment := retargetDotEnv(svc.ComposeFragment, s.EnvFilePath(env))
		return indent(fragment, 4), vols, nil
	default:
		return "", nil, fmt.Errorf("unknown source %q", svc.SourceType)
	}

	if svc.Type == database.ServiceDatabase {
		// Image and DataPath come from the row, not the catalog: the stored
		// reference carries the version the user picked, and re-deriving it
		// from the engine's default tag would move a running database.
		rendered, err := engines.Render(engines.Spec{
			Engine:   svc.Engine,
			Name:     svc.ComposeServiceName,
			Image:    svc.Image,
			DataPath: svc.DataPath,
			EnvFile:  s.ServiceEnvFilePath(env, svc.ComposeServiceName),
		})
		if err != nil {
			return "", nil, err
		}
		var vols []string
		if rendered.Volume != "" {
			vols = []string{rendered.Volume}
		}
		return rendered.Fragment, vols, nil
	}

	var b strings.Builder
	switch svc.SourceType {
	case database.ServiceImage:
		image, err := engines.ValidateImage(svc.Image)
		if err != nil {
			return "", nil, err
		}
		fmt.Fprintf(&b, "    image: %s\n", image)
	case database.ServiceGit:
		// Quoted like env_file below: build_path may legally hold a space or a
		// '#', either of which changes which directory compose reads.
		buildContext := filepath.Join(s.ServiceDir(env, svc.ComposeServiceName), "repository", svc.BuildPath)
		fmt.Fprintf(&b, "    build:\n      context: %q\n", buildContext)
	}
	b.WriteString("    restart: unless-stopped\n")
	fmt.Fprintf(&b, "    env_file: [%q]\n", s.ServiceEnvFilePath(env, svc.ComposeServiceName))
	return b.String(), nil, nil
}

// writeServiceEnv materialises a managed service's environment next to the
// overlay, with the same 0600 the project env file uses.
func (s *Service) writeServiceEnv(ctx context.Context, env *database.Environment, svc database.Service) error {
	vars, err := s.ServiceVariables(ctx, svc.ID)
	if err != nil {
		return err
	}
	return writeEnvFile(s.ServiceEnvFilePath(env, svc.ComposeServiceName), vars)
}

// indent shifts a YAML block so it can sit under a deeper key. Blank lines stay
// blank rather than becoming trailing whitespace.
func indent(block string, spaces int) string {
	pad := strings.Repeat(" ", spaces)
	lines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) == "" {
			lines[i] = ""
			continue
		}
		lines[i] = pad + line
	}
	return strings.Join(lines, "\n") + "\n"
}

// retargetDotEnv points a fragment's env_file: .env at the project env file,
// which is what the Environment tab writes.
func retargetDotEnv(fragment, envPath string) string {
	q := fmt.Sprintf("%q", envPath)
	for _, pair := range [][2]string{
		{"- .env", "- " + q},
		{"- '.env'", "- " + q},
		{`- ".env"`, "- " + q},
		{"env_file: .env", "env_file: " + q},
		{"env_file: [.env]", "env_file: [" + q + "]"},
	} {
		fragment = strings.ReplaceAll(fragment, pair[0], pair[1])
	}
	return fragment
}

func namedVolumes(fragment string) ([]string, error) {
	lines := strings.Split(fragment, "\n")
	keyIndent := -1
	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if trim == "" || strings.HasPrefix(trim, "#") || strings.HasPrefix(trim, "-") {
			continue
		}
		ind := len(line) - len(strings.TrimLeft(line, " \t"))
		if keyIndent < 0 || ind < keyIndent {
			keyIndent = ind
		}
	}
	if keyIndent < 0 {
		return nil, nil
	}
	inVolumes := false
	var names []string
	seen := map[string]struct{}{}
	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if trim == "" || strings.HasPrefix(trim, "#") {
			continue
		}
		ind := len(line) - len(strings.TrimLeft(line, " \t"))
		if ind == keyIndent {
			inVolumes = strings.HasPrefix(trim, "volumes:")
			if !inVolumes {
				continue
			}
			rest := strings.TrimSpace(strings.TrimPrefix(trim, "volumes:"))
			if rest == "" {
				continue
			}
			inVolumes = false
			if err := appendNamedVolume(rest, &names, seen); err != nil {
				return nil, err
			}
			continue
		}
		if !inVolumes || ind <= keyIndent || !strings.HasPrefix(trim, "-") {
			continue
		}
		entry := strings.TrimSpace(strings.TrimPrefix(trim, "-"))
		if err := appendNamedVolume(entry, &names, seen); err != nil {
			return nil, err
		}
	}
	return names, nil
}

func appendNamedVolume(entry string, names *[]string, seen map[string]struct{}) error {
	src := namedVolumeSource(entry)
	if src == "" {
		return nil
	}
	if err := security.ValidateServiceName(src); err != nil {
		return fmt.Errorf("volume %q: %w", src, err)
	}
	if _, ok := seen[src]; ok {
		return nil
	}
	seen[src] = struct{}{}
	*names = append(*names, src)
	return nil
}

func namedVolumeSource(entry string) string {
	entry = strings.Trim(strings.TrimSpace(entry), `"'`)
	if entry == "" {
		return ""
	}
	if strings.HasPrefix(entry, "[") && strings.HasSuffix(entry, "]") {
		return namedVolumeSource(strings.TrimSpace(entry[1 : len(entry)-1]))
	}
	if strings.HasPrefix(entry, "./") || strings.HasPrefix(entry, "/") || strings.HasPrefix(entry, "~/") {
		return ""
	}
	src, _, ok := strings.Cut(entry, ":")
	if !ok {
		return ""
	}
	src = strings.Trim(strings.TrimSpace(src), `"'`)
	switch src {
	case "", "type", "source", "target", "read_only":
		return ""
	}
	if strings.Contains(src, "/") {
		return ""
	}
	return src
}
