package projects

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vexdock/platform/manager/internal/database"
	"github.com/vexdock/platform/manager/internal/engines"
)

// overlayFileName is the compose file the manager writes from the service rows
// the dashboard owns. It is layered over the project's own compose file with a
// second --file flag, so an imported compose keeps working untouched and can
// still gain a database next to it.
const overlayFileName = "managed.yml"

// servicesDirName holds one checkout and one env file per managed service.
const servicesDirName = "services"

// ServiceDir is where a managed service keeps its own state, currently its git
// checkout. Kept separate from the project-level repository/ so two services
// can build from two different repositories.
func (s *Service) ServiceDir(p *database.Project, name string) string {
	return filepath.Join(s.cfg.ProjectDir(p.ID), servicesDirName, name)
}

// ServiceEnvFilePath is the env file a managed service hands to its container.
// Per service rather than per project so two Postgres services in one project
// can each define POSTGRES_PASSWORD.
func (s *Service) ServiceEnvFilePath(p *database.Project, name string) string {
	return filepath.Join(s.cfg.ProjectDir(p.ID), servicesDirName, name+".env")
}

// WriteOverlay renders every managed service of a project into the overlay
// compose file and writes each service's env file alongside it. It returns the
// overlay path, or an empty string when the project has no managed services and
// the project's own compose file is the whole story.
func (s *Service) WriteOverlay(ctx context.Context, p *database.Project) (string, error) {
	all, err := s.db.ListServices(ctx, p.ID)
	if err != nil {
		return "", err
	}
	managed := make([]database.Service, 0, len(all))
	for _, svc := range all {
		// An application whose source is still unanswered has nothing to render,
		// and emitting an empty service would fail the whole project's deploy.
		if svc.Managed() && svc.SourceType != database.ServiceUnconfigured {
			managed = append(managed, svc)
		}
	}
	path := filepath.Join(s.cfg.ProjectDir(p.ID), overlayFileName)
	if len(managed) == 0 {
		// Leaving a stale overlay behind would resurrect a deleted service on
		// the next deploy.
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return "", err
		}
		return "", nil
	}
	sort.Slice(managed, func(i, j int) bool {
		return managed[i].ComposeServiceName < managed[j].ComposeServiceName
	})

	if err := os.MkdirAll(filepath.Join(s.cfg.ProjectDir(p.ID), servicesDirName), 0o750); err != nil {
		return "", err
	}

	var body strings.Builder
	body.WriteString("# Generated by vexdock. Edits are overwritten on deploy.\nservices:\n")
	volumes := []string{}
	for _, svc := range managed {
		if err := s.writeServiceEnv(ctx, p, svc); err != nil {
			return "", err
		}
		fragment, volume, err := s.renderService(p, svc)
		if err != nil {
			return "", fmt.Errorf("service %s: %w", svc.ComposeServiceName, err)
		}
		// The catalog fragments are raw string literals that stop on their last
		// content character, so the next service's key would land on the previous
		// one's last line. Normalise here, where all three render branches meet.
		fmt.Fprintf(&body, "  %s:\n%s\n", svc.ComposeServiceName, strings.TrimRight(fragment, "\n"))
		if volume != "" {
			volumes = append(volumes, volume)
		}
	}
	if len(volumes) > 0 {
		body.WriteString("\nvolumes:\n")
		for _, v := range volumes {
			fmt.Fprintf(&body, "  %s: {}\n", v)
		}
	}
	// Same temp-and-rename as nginx and acme use: docker compose reads this
	// file, and a half-written one fails the whole project, not one service.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body.String()), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", err
	}
	return path, nil
}

// renderService turns one service row into its compose body, indented four
// spaces, plus the named volume it needs declared at the top level.
func (s *Service) renderService(p *database.Project, svc database.Service) (string, string, error) {
	switch svc.SourceType {
	case database.ServiceImage, database.ServiceGit:
	case database.ServiceCompose:
		return indent(svc.ComposeFragment, 4), "", nil
	default:
		return "", "", fmt.Errorf("unknown source %q", svc.SourceType)
	}

	if svc.Type == database.ServiceDatabase {
		// Image and DataPath come from the row, not the catalog: the stored
		// reference carries the version the user picked, and re-deriving it
		// from the engine's default tag would move a running database.
		rendered, err := engines.Render(engines.Spec{
			Engine:   svc.Engine,
			Name:     svc.ComposeServiceName,
			Image:    svc.Image,
			DataPath: svc.DataPath,
			EnvFile:  s.ServiceEnvFilePath(p, svc.ComposeServiceName),
		})
		if err != nil {
			return "", "", err
		}
		return rendered.Fragment, rendered.Volume, nil
	}

	var b strings.Builder
	switch svc.SourceType {
	case database.ServiceImage:
		image, err := engines.ValidateImage(svc.Image)
		if err != nil {
			return "", "", err
		}
		fmt.Fprintf(&b, "    image: %s\n", image)
	case database.ServiceGit:
		// Quoted like env_file below: build_path may legally hold a space or a
		// '#', either of which changes which directory compose reads.
		buildContext := filepath.Join(s.ServiceDir(p, svc.ComposeServiceName), "repository", svc.BuildPath)
		fmt.Fprintf(&b, "    build:\n      context: %q\n", buildContext)
	}
	b.WriteString("    restart: unless-stopped\n")
	fmt.Fprintf(&b, "    env_file: [%q]\n", s.ServiceEnvFilePath(p, svc.ComposeServiceName))
	return b.String(), "", nil
}

// writeServiceEnv materialises a managed service's environment next to the
// overlay, with the same 0600 the project env file uses.
func (s *Service) writeServiceEnv(ctx context.Context, p *database.Project, svc database.Service) error {
	vars, err := s.ServiceEnvironment(ctx, svc.ID, false)
	if err != nil {
		return err
	}
	return writeEnvFile(s.ServiceEnvFilePath(p, svc.ComposeServiceName), vars)
}

// indent shifts a YAML block so it can sit under a deeper key. Blank lines stay
// blank rather than becoming trailing whitespace.
func indent(block string, spaces int) string {
	pad := strings.Repeat(" ", spaces)
	lines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) == "" {
			lines[i] = ""
			continue
		}
		lines[i] = pad + line
	}
	return strings.Join(lines, "\n") + "\n"
}
