/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'
import { Route as DockerContainersRouteImport } from './routes/docker.containers'
import { Route as DockerImagesRouteImport } from './routes/docker.images'
import { Route as DockerNetworksRouteImport } from './routes/docker.networks'
import { Route as DockerVolumesRouteImport } from './routes/docker.volumes'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as SystemAuditRouteImport } from './routes/system.audit'
import { Route as SystemBackupsRouteImport } from './routes/system.backups'
import { Route as SystemCertificatesRouteImport } from './routes/system.certificates'
import { Route as SystemDockerRouteImport } from './routes/system.docker'
import { Route as SystemSettingsRouteImport } from './routes/system.settings'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdDeploymentsRouteImport } from './routes/projects.$projectId.deployments'
import { Route as ProjectsProjectIdDomainsRouteImport } from './routes/projects.$projectId.domains'
import { Route as ProjectsProjectIdEnvironmentRouteImport } from './routes/projects.$projectId.environment'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as SystemSettingsIndexRouteImport } from './routes/system.settings.index'
import { Route as SystemSettingsAboutRouteImport } from './routes/system.settings.about'
import { Route as SystemSettingsRegistriesRouteImport } from './routes/system.settings.registries'
import { Route as SystemSettingsTokensRouteImport } from './routes/system.settings.tokens'
import { Route as ProjectsProjectIdServicesServiceIdRouteImport } from './routes/projects.$projectId.services.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerContainersRoute = DockerContainersRouteImport.update({
  id: '/docker/containers',
  path: '/docker/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerImagesRoute = DockerImagesRouteImport.update({
  id: '/docker/images',
  path: '/docker/images',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerNetworksRoute = DockerNetworksRouteImport.update({
  id: '/docker/networks',
  path: '/docker/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerVolumesRoute = DockerVolumesRouteImport.update({
  id: '/docker/volumes',
  path: '/docker/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAuditRoute = SystemAuditRouteImport.update({
  id: '/system/audit',
  path: '/system/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemBackupsRoute = SystemBackupsRouteImport.update({
  id: '/system/backups',
  path: '/system/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCertificatesRoute = SystemCertificatesRouteImport.update({
  id: '/system/certificates',
  path: '/system/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDockerRoute = SystemDockerRouteImport.update({
  id: '/system/docker',
  path: '/system/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDeploymentsRoute =
  ProjectsProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDomainsRoute =
  ProjectsProjectIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEnvironmentRoute =
  ProjectsProjectIdEnvironmentRouteImport.update({
    id: '/environment',
    path: '/environment',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const SystemSettingsIndexRoute = SystemSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemSettingsRoute,
} as any)
const SystemSettingsAboutRoute = SystemSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SystemSettingsRoute,
} as any)
const SystemSettingsRegistriesRoute =
  SystemSettingsRegistriesRouteImport.update({
    id: '/registries',
    path: '/registries',
    getParentRoute: () => SystemSettingsRoute,
  } as any)
const SystemSettingsTokensRoute = SystemSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => SystemSettingsRoute,
} as any)
const ProjectsProjectIdServicesServiceIdRoute =
  ProjectsProjectIdServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/docker/containers': typeof DockerContainersRoute
  '/docker/images': typeof DockerImagesRoute
  '/docker/networks': typeof DockerNetworksRoute
  '/docker/volumes': typeof DockerVolumesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/system/audit': typeof SystemAuditRoute
  '/system/backups': typeof SystemBackupsRoute
  '/system/certificates': typeof SystemCertificatesRoute
  '/system/docker': typeof SystemDockerRoute
  '/system/settings': typeof SystemSettingsRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRoute
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/system/settings/about': typeof SystemSettingsAboutRoute
  '/system/settings/registries': typeof SystemSettingsRegistriesRoute
  '/system/settings/tokens': typeof SystemSettingsTokensRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/system/settings/': typeof SystemSettingsIndexRoute
  '/projects/$projectId/services/$serviceId': typeof ProjectsProjectIdServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/docker/containers': typeof DockerContainersRoute
  '/docker/images': typeof DockerImagesRoute
  '/docker/networks': typeof DockerNetworksRoute
  '/docker/volumes': typeof DockerVolumesRoute
  '/system/audit': typeof SystemAuditRoute
  '/system/backups': typeof SystemBackupsRoute
  '/system/certificates': typeof SystemCertificatesRoute
  '/system/docker': typeof SystemDockerRoute
  '/projects': typeof ProjectsIndexRoute
  '/system': typeof SystemIndexRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRoute
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/system/settings/about': typeof SystemSettingsAboutRoute
  '/system/settings/registries': typeof SystemSettingsRegistriesRoute
  '/system/settings/tokens': typeof SystemSettingsTokensRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/system/settings': typeof SystemSettingsIndexRoute
  '/projects/$projectId/services/$serviceId': typeof ProjectsProjectIdServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/docker/containers': typeof DockerContainersRoute
  '/docker/images': typeof DockerImagesRoute
  '/docker/networks': typeof DockerNetworksRoute
  '/docker/volumes': typeof DockerVolumesRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/system/audit': typeof SystemAuditRoute
  '/system/backups': typeof SystemBackupsRoute
  '/system/certificates': typeof SystemCertificatesRoute
  '/system/docker': typeof SystemDockerRoute
  '/system/settings': typeof SystemSettingsRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/system/': typeof SystemIndexRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/domains': typeof ProjectsProjectIdDomainsRoute
  '/projects/$projectId/environment': typeof ProjectsProjectIdEnvironmentRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/system/settings/about': typeof SystemSettingsAboutRoute
  '/system/settings/registries': typeof SystemSettingsRegistriesRoute
  '/system/settings/tokens': typeof SystemSettingsTokensRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/system/settings/': typeof SystemSettingsIndexRoute
  '/projects/$projectId/services/$serviceId': typeof ProjectsProjectIdServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/domains'
    | '/login'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/docker/containers'
    | '/docker/images'
    | '/docker/networks'
    | '/docker/volumes'
    | '/projects/$projectId'
    | '/system/audit'
    | '/system/backups'
    | '/system/certificates'
    | '/system/docker'
    | '/system/settings'
    | '/projects/'
    | '/system/'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/settings'
    | '/system/settings/about'
    | '/system/settings/registries'
    | '/system/settings/tokens'
    | '/projects/$projectId/'
    | '/system/settings/'
    | '/projects/$projectId/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/domains'
    | '/login'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/docker/containers'
    | '/docker/images'
    | '/docker/networks'
    | '/docker/volumes'
    | '/system/audit'
    | '/system/backups'
    | '/system/certificates'
    | '/system/docker'
    | '/projects'
    | '/system'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/settings'
    | '/system/settings/about'
    | '/system/settings/registries'
    | '/system/settings/tokens'
    | '/projects/$projectId'
    | '/system/settings'
    | '/projects/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/domains'
    | '/login'
    | '/setup'
    | '/deployments/$deploymentId'
    | '/docker/containers'
    | '/docker/images'
    | '/docker/networks'
    | '/docker/volumes'
    | '/projects/$projectId'
    | '/system/audit'
    | '/system/backups'
    | '/system/certificates'
    | '/system/docker'
    | '/system/settings'
    | '/projects/'
    | '/system/'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/environment'
    | '/projects/$projectId/settings'
    | '/system/settings/about'
    | '/system/settings/registries'
    | '/system/settings/tokens'
    | '/projects/$projectId/'
    | '/system/settings/'
    | '/projects/$projectId/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DomainsRoute: typeof DomainsRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
  DockerContainersRoute: typeof DockerContainersRoute
  DockerImagesRoute: typeof DockerImagesRoute
  DockerNetworksRoute: typeof DockerNetworksRoute
  DockerVolumesRoute: typeof DockerVolumesRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  SystemAuditRoute: typeof SystemAuditRoute
  SystemBackupsRoute: typeof SystemBackupsRoute
  SystemCertificatesRoute: typeof SystemCertificatesRoute
  SystemDockerRoute: typeof SystemDockerRoute
  SystemSettingsRoute: typeof SystemSettingsRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/containers': {
      id: '/docker/containers'
      path: '/docker/containers'
      fullPath: '/docker/containers'
      preLoaderRoute: typeof DockerContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/images': {
      id: '/docker/images'
      path: '/docker/images'
      fullPath: '/docker/images'
      preLoaderRoute: typeof DockerImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/networks': {
      id: '/docker/networks'
      path: '/docker/networks'
      fullPath: '/docker/networks'
      preLoaderRoute: typeof DockerNetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/volumes': {
      id: '/docker/volumes'
      path: '/docker/volumes'
      fullPath: '/docker/volumes'
      preLoaderRoute: typeof DockerVolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/audit': {
      id: '/system/audit'
      path: '/system/audit'
      fullPath: '/system/audit'
      preLoaderRoute: typeof SystemAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/backups': {
      id: '/system/backups'
      path: '/system/backups'
      fullPath: '/system/backups'
      preLoaderRoute: typeof SystemBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/certificates': {
      id: '/system/certificates'
      path: '/system/certificates'
      fullPath: '/system/certificates'
      preLoaderRoute: typeof SystemCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/docker': {
      id: '/system/docker'
      path: '/system/docker'
      fullPath: '/system/docker'
      preLoaderRoute: typeof SystemDockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/settings': {
      id: '/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployments': {
      id: '/projects/$projectId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/deployments'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/domains': {
      id: '/projects/$projectId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/domains'
      preLoaderRoute: typeof ProjectsProjectIdDomainsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/environment': {
      id: '/projects/$projectId/environment'
      path: '/environment'
      fullPath: '/projects/$projectId/environment'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/system/settings/': {
      id: '/system/settings/'
      path: '/'
      fullPath: '/system/settings/'
      preLoaderRoute: typeof SystemSettingsIndexRouteImport
      parentRoute: typeof SystemSettingsRoute
    }
    '/system/settings/about': {
      id: '/system/settings/about'
      path: '/about'
      fullPath: '/system/settings/about'
      preLoaderRoute: typeof SystemSettingsAboutRouteImport
      parentRoute: typeof SystemSettingsRoute
    }
    '/system/settings/registries': {
      id: '/system/settings/registries'
      path: '/registries'
      fullPath: '/system/settings/registries'
      preLoaderRoute: typeof SystemSettingsRegistriesRouteImport
      parentRoute: typeof SystemSettingsRoute
    }
    '/system/settings/tokens': {
      id: '/system/settings/tokens'
      path: '/tokens'
      fullPath: '/system/settings/tokens'
      preLoaderRoute: typeof SystemSettingsTokensRouteImport
      parentRoute: typeof SystemSettingsRoute
    }
    '/projects/$projectId/services/$serviceId': {
      id: '/projects/$projectId/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/projects/$projectId/services/$serviceId'
      preLoaderRoute: typeof ProjectsProjectIdServicesServiceIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDeploymentsRoute: typeof ProjectsProjectIdDeploymentsRoute
  ProjectsProjectIdDomainsRoute: typeof ProjectsProjectIdDomainsRoute
  ProjectsProjectIdEnvironmentRoute: typeof ProjectsProjectIdEnvironmentRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdServicesServiceIdRoute: typeof ProjectsProjectIdServicesServiceIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDeploymentsRoute: ProjectsProjectIdDeploymentsRoute,
  ProjectsProjectIdDomainsRoute: ProjectsProjectIdDomainsRoute,
  ProjectsProjectIdEnvironmentRoute: ProjectsProjectIdEnvironmentRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdServicesServiceIdRoute:
    ProjectsProjectIdServicesServiceIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface SystemSettingsRouteChildren {
  SystemSettingsAboutRoute: typeof SystemSettingsAboutRoute
  SystemSettingsRegistriesRoute: typeof SystemSettingsRegistriesRoute
  SystemSettingsTokensRoute: typeof SystemSettingsTokensRoute
  SystemSettingsIndexRoute: typeof SystemSettingsIndexRoute
}

const SystemSettingsRouteChildren: SystemSettingsRouteChildren = {
  SystemSettingsAboutRoute: SystemSettingsAboutRoute,
  SystemSettingsRegistriesRoute: SystemSettingsRegistriesRoute,
  SystemSettingsTokensRoute: SystemSettingsTokensRoute,
  SystemSettingsIndexRoute: SystemSettingsIndexRoute,
}

const SystemSettingsRouteWithChildren = SystemSettingsRoute._addFileChildren(
  SystemSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DomainsRoute: DomainsRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
  DockerContainersRoute: DockerContainersRoute,
  DockerImagesRoute: DockerImagesRoute,
  DockerNetworksRoute: DockerNetworksRoute,
  DockerVolumesRoute: DockerVolumesRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  SystemAuditRoute: SystemAuditRoute,
  SystemBackupsRoute: SystemBackupsRoute,
  SystemCertificatesRoute: SystemCertificatesRoute,
  SystemDockerRoute: SystemDockerRoute,
  SystemSettingsRoute: SystemSettingsRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
