// Package nginx renders and safely applies the reverse-proxy configuration.
// Users never write Nginx config: they add a domain and the platform generates,
// validates and reloads.
package nginx

import (
	"fmt"
	"sort"
	"strings"
)

// Upstream is one generated vhost: a hostname routed to a container alias on
// the shared proxy network.
type Upstream struct {
	Hostname      string
	Alias         string
	Port          int
	HTTPS         bool
	RedirectHTTPS bool
	// CertDir is the directory holding fullchain.pem and privkey.pem.
	CertDir string
	// Analytics serves the visit beacon from this hostname and injects it into
	// HTML responses, so the deployed app needs no script tag of its own.
	Analytics bool
}

// ChallengeRoot is where the ACME HTTP-01 tokens are written; Nginx serves it
// for every hostname so issuance works before a certificate exists.
const ChallengeRoot = "/acme-challenge"

// AuthUpstream is the better-auth service, which serves /api/auth.
const AuthUpstream = "auth:8081"

// ManagerUpstream is the manager API, reachable from Nginx on the internal
// network only.
const ManagerUpstream = "manager:8080"

// Analytics beacon paths, served from the visited site so no request leaves it.
const (
	BeaconPath  = "/_vx.js"
	CollectPath = "/_vx"
)

// FileName is the deterministic config filename for a hostname.
func FileName(hostname string) string { return hostname + ".conf" }

// Render produces the full server block(s) for one upstream.
//
// proxy_pass goes through a variable plus the Docker embedded resolver so the
// address is re-resolved at request time: a recreated container gets a new IP
// and stale caching would otherwise 502 until a reload.
func Render(u Upstream) string {
	var b strings.Builder
	target := fmt.Sprintf("http://%s:%d", u.Alias, u.Port)

	b.WriteString("# generated by the platform - do not edit\n")
	b.WriteString("server {\n")
	b.WriteString("    listen 80;\n    listen [::]:80;\n")
	fmt.Fprintf(&b, "    server_name %s;\n\n", u.Hostname)
	b.WriteString(challengeLocation())

	if u.HTTPS && u.RedirectHTTPS {
		b.WriteString("\n    location / {\n        return 301 https://$host$request_uri;\n    }\n}\n")
	} else {
		b.WriteString("\n")
		if u.Analytics {
			b.WriteString(analyticsLocations())
		}
		b.WriteString(proxyLocation(target, u.Analytics))
		b.WriteString("}\n")
	}

	if !u.HTTPS {
		return b.String()
	}

	b.WriteString("\nserver {\n")
	b.WriteString("    listen 443 ssl;\n    listen [::]:443 ssl;\n    http2 on;\n")
	fmt.Fprintf(&b, "    server_name %s;\n\n", u.Hostname)
	fmt.Fprintf(&b, "    ssl_certificate     %s/fullchain.pem;\n", u.CertDir)
	fmt.Fprintf(&b, "    ssl_certificate_key %s/privkey.pem;\n", u.CertDir)
	b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
	b.WriteString("    ssl_session_cache shared:SSL:10m;\n")
	b.WriteString("    ssl_session_timeout 1d;\n\n")
	b.WriteString(challengeLocation())
	b.WriteString("\n")
	if u.Analytics {
		b.WriteString(analyticsLocations())
	}
	b.WriteString(proxyLocation(target, u.Analytics))
	b.WriteString("}\n")
	return b.String()
}

func challengeLocation() string {
	return "    location ^~ /.well-known/acme-challenge/ {\n" +
		"        root " + ChallengeRoot + ";\n" +
		"        default_type \"text/plain\";\n" +
		"    }\n"
}

// analyticsLocations keeps the beacon first-party: the script and the hit both
// come from the visited hostname and Nginx forwards them to the manager, so no
// cross-origin request and no third-party domain is involved.
func analyticsLocations() string {
	var b strings.Builder
	fmt.Fprintf(&b, "    location = %s {\n", BeaconPath)
	fmt.Fprintf(&b, "        proxy_pass http://%s/api/collect.js;\n", ManagerUpstream)
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("    }\n\n")

	fmt.Fprintf(&b, "    location = %s {\n", CollectPath)
	b.WriteString("        limit_req zone=api_limit burst=20 nodelay;\n")
	fmt.Fprintf(&b, "        proxy_pass http://%s/api/collect;\n", ManagerUpstream)
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("    }\n\n")
	return b.String()
}

func proxyLocation(target string, analytics bool) string {
	var b strings.Builder
	b.WriteString("    location / {\n")
	b.WriteString("        resolver 127.0.0.11 valid=10s ipv6=off;\n")
	fmt.Fprintf(&b, "        set $upstream %s;\n", target)
	b.WriteString("        proxy_pass $upstream;\n\n")
	b.WriteString("        proxy_http_version 1.1;\n\n")
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n\n")
	b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
	b.WriteString("        proxy_set_header Connection $connection_upgrade;\n\n")
	// SSE and long-poll endpoints must not be buffered or timed out early.
	b.WriteString("        proxy_buffering off;\n")
	b.WriteString("        proxy_cache off;\n")
	b.WriteString("        proxy_read_timeout 3600s;\n")
	b.WriteString("        proxy_send_timeout 3600s;\n")
	if analytics {
		// sub_filter cannot rewrite a compressed body, so the upstream is asked
		// for plain HTML; Nginx still gzips it on the way out.
		b.WriteString("\n        proxy_set_header Accept-Encoding \"\";\n")
		b.WriteString("        sub_filter_types text/html;\n")
		b.WriteString("        sub_filter_once on;\n")
		fmt.Fprintf(&b, "        sub_filter '</head>' '<script defer src=\"%s\"></script></head>';\n", BeaconPath)
	}
	b.WriteString("    }\n")
	return b.String()
}

// RenderDashboard exposes the panel itself on a user-chosen hostname, serving
// the static UI and proxying /api to the manager.
func RenderDashboard(hostname, managerAddr, webRoot string, https bool, certDir string) string {
	var b strings.Builder
	b.WriteString("# generated by the platform - dashboard vhost\n")
	b.WriteString("server {\n    listen 80;\n    listen [::]:80;\n")
	fmt.Fprintf(&b, "    server_name %s;\n\n", hostname)
	b.WriteString(challengeLocation())
	if https {
		b.WriteString("\n    location / {\n        return 301 https://$host$request_uri;\n    }\n}\n\n")
		b.WriteString("server {\n    listen 443 ssl;\n    listen [::]:443 ssl;\n    http2 on;\n")
		fmt.Fprintf(&b, "    server_name %s;\n\n", hostname)
		fmt.Fprintf(&b, "    ssl_certificate     %s/fullchain.pem;\n", certDir)
		fmt.Fprintf(&b, "    ssl_certificate_key %s/privkey.pem;\n", certDir)
		b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n\n")
	} else {
		b.WriteString("\n")
	}
	b.WriteString(dashboardBody(managerAddr, webRoot))
	b.WriteString("}\n")
	return b.String()
}

func dashboardBody(managerAddr, webRoot string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "    root %s;\n", webRoot)
	b.WriteString("    index index.html;\n\n")

	// Credential endpoints are throttled here too. Moving the panel to its own
	// domain must not quietly drop the login limit that :3000 has.
	b.WriteString("    location ~ ^/api/auth/(sign-in|sign-up|forget-password|reset-password) {\n")
	b.WriteString("        limit_req zone=login_limit burst=5 nodelay;\n")
	fmt.Fprintf(&b, "        proxy_pass http://%s;\n", AuthUpstream)
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("    }\n\n")

	// Authentication is a separate service; everything else is the manager.
	b.WriteString("    location /api/auth/ {\n")
	b.WriteString("        limit_req zone=api_limit burst=60 nodelay;\n")
	fmt.Fprintf(&b, "        proxy_pass http://%s;\n", AuthUpstream)
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("    }\n\n")

	b.WriteString("    location /api/ {\n")
	b.WriteString("        limit_req zone=api_limit burst=60 nodelay;\n")
	fmt.Fprintf(&b, "        proxy_pass http://%s;\n", managerAddr)
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Host $http_host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
	b.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
	b.WriteString("        proxy_buffering off;\n")
	b.WriteString("        proxy_read_timeout 3600s;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location / {\n        try_files $uri $uri/ /index.html;\n    }\n")
	return b.String()
}

// Alias is the stable network alias for one compose service of one environment.
// Container ids change on every recreate; this name does not. It is keyed on
// the environment because production and staging can both run a service called
// web, and a shared alias would send traffic to whichever attached last.
func Alias(environmentID, service string) string {
	safe := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			return r
		case r >= 'A' && r <= 'Z':
			return r + 32
		default:
			return '-'
		}
	}, service)
	return fmt.Sprintf("p_%s_%s", strings.ToLower(environmentID), safe)
}

// SortedFileNames gives a deterministic order for diffing a rendered set.
func SortedFileNames(files map[string]string) []string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
